// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrbSWSlSz9uDrsCPYOl2BVlqYgZlB8OM',
    appId: '1:792857956324:web:ec0e4c9995fb96d92581f1',
    messagingSenderId: '792857956324',
    projectId: 'buka-app-ddf88',
    authDomain: 'buka-app-ddf88.firebaseapp.com',
    storageBucket: 'buka-app-ddf88.firebasestorage.app',
    measurementId: 'G-EJVVW0J5YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1lQBGdFUmYfOXOIrQjSEeGdJvNqfmeY',
    appId: '1:792857956324:android:9d0aadafcd0f444c2581f1',
    messagingSenderId: '792857956324',
    projectId: 'buka-app-ddf88',
    storageBucket: 'buka-app-ddf88.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcYHq5mjZNUB4ulVWWUoWjylbJB8a1PMY',
    appId: '1:792857956324:ios:3e9f52ec350ad0412581f1',
    messagingSenderId: '792857956324',
    projectId: 'buka-app-ddf88',
    storageBucket: 'buka-app-ddf88.firebasestorage.app',
    iosClientId: '792857956324-0mnd5mv5qm88tvpdpp4kss8opav0ri2k.apps.googleusercontent.com',
    iosBundleId: 'TrabalhoTCC.com.bibliotecaVirtualNh',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcYHq5mjZNUB4ulVWWUoWjylbJB8a1PMY',
    appId: '1:792857956324:ios:3e9f52ec350ad0412581f1',
    messagingSenderId: '792857956324',
    projectId: 'buka-app-ddf88',
    storageBucket: 'buka-app-ddf88.firebasestorage.app',
    iosClientId: '792857956324-0mnd5mv5qm88tvpdpp4kss8opav0ri2k.apps.googleusercontent.com',
    iosBundleId: 'TrabalhoTCC.com.bibliotecaVirtualNh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrbSWSlSz9uDrsCPYOl2BVlqYgZlB8OM',
    appId: '1:792857956324:web:3067138bb374320b2581f1',
    messagingSenderId: '792857956324',
    projectId: 'buka-app-ddf88',
    authDomain: 'buka-app-ddf88.firebaseapp.com',
    storageBucket: 'buka-app-ddf88.firebasestorage.app',
    measurementId: 'G-5ZZSBPMG1T',
  );
}
